# Generated by Django 4.0.3 on 2022-03-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('info', models.CharField(max_length=100)),
                ('slug', models.CharField(default='1', editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('25', '25cm'), ('30', '30cm'), ('35', '35cm')], max_length=2)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('pizza_slug', models.CharField(default='1', editable=False, max_length=100)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pizzeria.pizza')),
            ],
        ),
    ]
