# Generated by Django 4.0.3 on 2022-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatopping',
            name='slug',
            field=models.CharField(default='1', editable=False, max_length=100, unique=True),
        ),
    ]
